<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Common\Models\" />
    <Folder Include="Common\Behaviors\" />
    <Folder Include="Editions\Commands\" />
    <Folder Include="Editions\Queries\" />
    <Folder Include="Inscriptions\Commands\" />
    <Folder Include="Inscriptions\Queries\" />
    <Folder Include="Paiements\Commands\" />
    <Folder Include="Paiements\Queries\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

</Project>
