// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260724203745_SeedDroitsCartesCompetences")]
    partial class SeedDroitsCartesCompetences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Badge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BadgeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BadgeImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BadgeNom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Programme")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BadgeCode")
                        .IsUnique();

                    b.ToTable("Badges");
                });

            modelBuilder.Entity("Domain.Entities.CarteCompetence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuteurCitation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BadgeId")
                        .HasColumnType("int");

                    b.Property<string>("Citation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CitationHumour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ContextePerso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContextePro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("Etape1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Etape2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Etape3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Etape4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Etape5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageCarteA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LienVideo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifieLe")
                        .HasColumnType("datetime2");

                    b.Property<int>("Niveau")
                        .HasColumnType("int");

                    b.Property<string>("Objectif1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Objectif2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Objectif3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Objectif4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tip1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tip2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tip3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tip4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tip5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitreDefi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitreTheorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TonDefi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BadgeId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CartesCompetences");
                });

            modelBuilder.Entity("Domain.Entities.DocumentLegal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateEffective")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstPublie")
                        .HasColumnType("bit");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Type", "Version")
                        .IsUnique();

                    b.ToTable("DocumentsLegaux");
                });

            modelBuilder.Entity("Domain.Entities.Droit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GroupeDroitId")
                        .HasColumnType("int");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RessourceId")
                        .HasColumnType("int");

                    b.Property<int>("TypeActionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupeDroitId");

                    b.HasIndex("TypeActionId");

                    b.HasIndex("RessourceId", "TypeActionId")
                        .IsUnique();

                    b.ToTable("Droits");
                });

            modelBuilder.Entity("Domain.Entities.GroupeDroit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GroupesDroit");
                });

            modelBuilder.Entity("Domain.Entities.Ressource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ressources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CONGRES",
                            Libelle = "Congrès"
                        },
                        new
                        {
                            Id = 2,
                            Code = "COMMANDE",
                            Libelle = "Commande"
                        },
                        new
                        {
                            Id = 3,
                            Code = "UTILISATEUR",
                            Libelle = "Utilisateur"
                        },
                        new
                        {
                            Id = 4,
                            Code = "ORGANISATION",
                            Libelle = "Organisation"
                        });
                });

            modelBuilder.Entity("Domain.Entities.TypeAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypesAction");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CONSULTER",
                            Libelle = "Consulter"
                        },
                        new
                        {
                            Id = 2,
                            Code = "CREER",
                            Libelle = "Créer"
                        },
                        new
                        {
                            Id = 3,
                            Code = "MODIFIER",
                            Libelle = "Modifier"
                        },
                        new
                        {
                            Id = 4,
                            Code = "SUPPRIMER",
                            Libelle = "Supprimer"
                        },
                        new
                        {
                            Id = 5,
                            Code = "VALIDER",
                            Libelle = "Valider"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Web.Data.AcceptationDocumentLegal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdresseIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateAcceptation")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentLegalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("DocumentLegalId");

                    b.ToTable("AcceptationsDocumentsLegaux");
                });

            modelBuilder.Entity("Web.Data.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Web.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("CiviliteId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("EstSuperAdministrateur")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Prenom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CiviliteId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Web.Data.CarteAttribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AttribueLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("AttribueParId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CarteCompetenceId")
                        .HasColumnType("int");

                    b.Property<string>("Contexte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstActif")
                        .HasColumnType("bit");

                    b.Property<string>("UtilisateurId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AttribueParId");

                    b.HasIndex("UtilisateurId");

                    b.HasIndex("CarteCompetenceId", "UtilisateurId")
                        .IsUnique();

                    b.ToTable("CarteAttributions");
                });

            modelBuilder.Entity("Web.Data.Civilite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstActif")
                        .HasColumnType("bit");

                    b.Property<string>("LibelleArticle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LibelleCourt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LibelleLong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ordre")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Civilites");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "M",
                            EstActif = true,
                            LibelleArticle = "à Monsieur",
                            LibelleCourt = "M.",
                            LibelleLong = "Monsieur",
                            Ordre = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "MME",
                            EstActif = true,
                            LibelleArticle = "à Madame",
                            LibelleCourt = "Mme",
                            LibelleLong = "Madame",
                            Ordre = 2
                        });
                });

            modelBuilder.Entity("Web.Data.Entities.Fonction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstActif")
                        .HasColumnType("bit");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Fonctions");
                });

            modelBuilder.Entity("Web.Data.Entities.Organisation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adresse2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeAdherent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodePostal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstActif")
                        .HasColumnType("bit");

                    b.Property<string>("RaisonSociale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelephoneStandard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ville")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("Web.Data.Entities.Scope", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstActif")
                        .HasColumnType("bit");

                    b.Property<int?>("OrganisationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("OrganisationId");

                    b.ToTable("Scopes");
                });

            modelBuilder.Entity("Web.Data.Rattachement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstActif")
                        .HasColumnType("bit");

                    b.Property<int?>("FonctionId")
                        .HasColumnType("int");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("FonctionId");

                    b.HasIndex("OrganisationId");

                    b.ToTable("Rattachements");
                });

            modelBuilder.Entity("Web.Data.RoleDroit", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DroitId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "DroitId");

                    b.HasIndex("DroitId");

                    b.ToTable("RoleDroits");
                });

            modelBuilder.Entity("Web.Data.RoleGroupeDroit", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GroupeDroitId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "GroupeDroitId");

                    b.HasIndex("GroupeDroitId");

                    b.ToTable("RoleGroupesDroit");
                });

            modelBuilder.Entity("Domain.Entities.CarteCompetence", b =>
                {
                    b.HasOne("Domain.Entities.Badge", "Badge")
                        .WithMany()
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Badge");
                });

            modelBuilder.Entity("Domain.Entities.Droit", b =>
                {
                    b.HasOne("Domain.Entities.GroupeDroit", "GroupeDroit")
                        .WithMany("Droits")
                        .HasForeignKey("GroupeDroitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.Ressource", "Ressource")
                        .WithMany("Droits")
                        .HasForeignKey("RessourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TypeAction", "TypeAction")
                        .WithMany("Droits")
                        .HasForeignKey("TypeActionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GroupeDroit");

                    b.Navigation("Ressource");

                    b.Navigation("TypeAction");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Web.Data.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Web.Data.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Web.Data.AcceptationDocumentLegal", b =>
                {
                    b.HasOne("Web.Data.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.DocumentLegal", "DocumentLegal")
                        .WithMany()
                        .HasForeignKey("DocumentLegalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("DocumentLegal");
                });

            modelBuilder.Entity("Web.Data.ApplicationUser", b =>
                {
                    b.HasOne("Web.Data.Civilite", "Civilite")
                        .WithMany()
                        .HasForeignKey("CiviliteId");

                    b.Navigation("Civilite");
                });

            modelBuilder.Entity("Web.Data.CarteAttribution", b =>
                {
                    b.HasOne("Web.Data.ApplicationUser", "AttribuePar")
                        .WithMany()
                        .HasForeignKey("AttribueParId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.CarteCompetence", "CarteCompetence")
                        .WithMany()
                        .HasForeignKey("CarteCompetenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Web.Data.ApplicationUser", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttribuePar");

                    b.Navigation("CarteCompetence");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Web.Data.Entities.Scope", b =>
                {
                    b.HasOne("Web.Data.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web.Data.Entities.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApplicationUser");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("Web.Data.Rattachement", b =>
                {
                    b.HasOne("Web.Data.ApplicationUser", "ApplicationUser")
                        .WithMany("Rattachements")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web.Data.Entities.Fonction", "Fonction")
                        .WithMany()
                        .HasForeignKey("FonctionId");

                    b.HasOne("Web.Data.Entities.Organisation", "Organisation")
                        .WithMany("Rattachements")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Fonction");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("Web.Data.RoleDroit", b =>
                {
                    b.HasOne("Domain.Entities.Droit", "Droit")
                        .WithMany()
                        .HasForeignKey("DroitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web.Data.ApplicationRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Droit");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Web.Data.RoleGroupeDroit", b =>
                {
                    b.HasOne("Domain.Entities.GroupeDroit", "GroupeDroit")
                        .WithMany()
                        .HasForeignKey("GroupeDroitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web.Data.ApplicationRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupeDroit");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.GroupeDroit", b =>
                {
                    b.Navigation("Droits");
                });

            modelBuilder.Entity("Domain.Entities.Ressource", b =>
                {
                    b.Navigation("Droits");
                });

            modelBuilder.Entity("Domain.Entities.TypeAction", b =>
                {
                    b.Navigation("Droits");
                });

            modelBuilder.Entity("Web.Data.ApplicationUser", b =>
                {
                    b.Navigation("Rattachements");
                });

            modelBuilder.Entity("Web.Data.Entities.Organisation", b =>
                {
                    b.Navigation("Rattachements");
                });
#pragma warning restore 612, 618
        }
    }
}
