// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Badge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BadgeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BadgeImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BadgeNom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Programme")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BadgeCode")
                        .IsUnique();

                    b.ToTable("Badges");
                });

            modelBuilder.Entity("Domain.Entities.CarteCompetence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuteurCitation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BadgeId")
                        .HasColumnType("int");

                    b.Property<string>("Citation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CitationHumour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ContextePerso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContextePro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("Etape1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Etape2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Etape3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Etape4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Etape5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageCarteA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LienVideo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifieLe")
                        .HasColumnType("datetime2");

                    b.Property<int>("Niveau")
                        .HasColumnType("int");

                    b.Property<string>("Objectif1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Objectif2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Objectif3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Objectif4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tip1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tip2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tip3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tip4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tip5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitreDefi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitreTheorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TonDefi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BadgeId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CartesCompetences");
                });

            modelBuilder.Entity("Domain.Entities.Challenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<int>("NombreEtapes")
                        .HasColumnType("int");

                    b.Property<string>("Slogan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.ToTable("Challenges");
                });

            modelBuilder.Entity("Domain.Entities.ChallengeEtape", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChallengeId")
                        .HasColumnType("int");

                    b.Property<string>("CompetenceCible")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefiIndividuel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroEtape")
                        .HasColumnType("int");

                    b.Property<string>("ObjectifPedagogique")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitreEtape")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId", "NumeroEtape")
                        .IsUnique();

                    b.ToTable("ChallengeEtapes");
                });

            modelBuilder.Entity("Domain.Entities.ChallengeEtapeCarte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarteCompetenceId")
                        .HasColumnType("int");

                    b.Property<int>("ChallengeEtapeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarteCompetenceId");

                    b.HasIndex("ChallengeEtapeId", "CarteCompetenceId")
                        .IsUnique();

                    b.ToTable("ChallengeEtapeCartes");
                });

            modelBuilder.Entity("Domain.Entities.DocumentLegal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateEffective")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstPublie")
                        .HasColumnType("bit");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Type", "Version")
                        .IsUnique();

                    b.ToTable("DocumentsLegaux");
                });

            modelBuilder.Entity("Domain.Entities.Droit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GroupeDroitId")
                        .HasColumnType("int");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RessourceId")
                        .HasColumnType("int");

                    b.Property<int>("TypeActionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupeDroitId");

                    b.HasIndex("TypeActionId");

                    b.HasIndex("RessourceId", "TypeActionId")
                        .IsUnique();

                    b.ToTable("Droits");
                });

            modelBuilder.Entity("Domain.Entities.GroupeDroit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GroupesDroit");
                });

            modelBuilder.Entity("Domain.Entities.Ressource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ressources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CONGRES",
                            Libelle = "Congrès"
                        },
                        new
                        {
                            Id = 2,
                            Code = "COMMANDE",
                            Libelle = "Commande"
                        },
                        new
                        {
                            Id = 3,
                            Code = "UTILISATEUR",
                            Libelle = "Utilisateur"
                        },
                        new
                        {
                            Id = 4,
                            Code = "ORGANISATION",
                            Libelle = "Organisation"
                        });
                });

            modelBuilder.Entity("Domain.Entities.TypeAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypesAction");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CONSULTER",
                            Libelle = "Consulter"
                        },
                        new
                        {
                            Id = 2,
                            Code = "CREER",
                            Libelle = "Créer"
                        },
                        new
                        {
                            Id = 3,
                            Code = "MODIFIER",
                            Libelle = "Modifier"
                        },
                        new
                        {
                            Id = 4,
                            Code = "SUPPRIMER",
                            Libelle = "Supprimer"
                        },
                        new
                        {
                            Id = 5,
                            Code = "VALIDER",
                            Libelle = "Valider"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Web.Data.AcceptationDocumentLegal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdresseIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateAcceptation")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentLegalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("DocumentLegalId");

                    b.ToTable("AcceptationsDocumentsLegaux");
                });

            modelBuilder.Entity("Web.Data.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Web.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("CiviliteId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("EstSuperAdministrateur")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Prenom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CiviliteId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Web.Data.BadgeSocialAttribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChallengeEtapeId")
                        .HasColumnType("int");

                    b.Property<int>("CohorteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAttribution")
                        .HasColumnType("datetime2");

                    b.Property<int>("TypeBadge")
                        .HasColumnType("int");

                    b.Property<string>("UtilisateurId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeEtapeId");

                    b.HasIndex("CohorteId");

                    b.HasIndex("UtilisateurId", "CohorteId", "ChallengeEtapeId", "TypeBadge")
                        .IsUnique();

                    b.ToTable("BadgeSocialAttributions");
                });

            modelBuilder.Entity("Web.Data.CarteAttribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AttribueLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("AttribueParId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CarteCompetenceId")
                        .HasColumnType("int");

                    b.Property<int?>("ChallengeEtapeId")
                        .HasColumnType("int");

                    b.Property<int?>("CohorteId")
                        .HasColumnType("int");

                    b.Property<string>("Contexte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstActif")
                        .HasColumnType("bit");

                    b.Property<int>("OrigineType")
                        .HasColumnType("int");

                    b.Property<string>("UtilisateurId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AttribueParId");

                    b.HasIndex("ChallengeEtapeId");

                    b.HasIndex("CohorteId");

                    b.HasIndex("UtilisateurId");

                    b.HasIndex("CarteCompetenceId", "UtilisateurId", "OrigineType", "CohorteId", "ChallengeEtapeId")
                        .IsUnique()
                        .HasFilter("[CohorteId] IS NOT NULL AND [ChallengeEtapeId] IS NOT NULL");

                    b.ToTable("CarteAttributions");
                });

            modelBuilder.Entity("Web.Data.Civilite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstActif")
                        .HasColumnType("bit");

                    b.Property<string>("LibelleArticle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LibelleCourt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LibelleLong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ordre")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Civilites");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "M",
                            EstActif = true,
                            LibelleArticle = "à Monsieur",
                            LibelleCourt = "M.",
                            LibelleLong = "Monsieur",
                            Ordre = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "MME",
                            EstActif = true,
                            LibelleArticle = "à Madame",
                            LibelleCourt = "Mme",
                            LibelleLong = "Madame",
                            Ordre = 2
                        });
                });

            modelBuilder.Entity("Web.Data.Cohorte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChallengeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLancement")
                        .HasColumnType("datetime2");

                    b.Property<int>("EtapeCourante")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrganisationId")
                        .HasColumnType("int");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("OrganisationId");

                    b.ToTable("Cohortes");
                });

            modelBuilder.Entity("Web.Data.CohorteEtapeValidation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CohorteId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroEtape")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValideLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("ValideParId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ValideParId");

                    b.HasIndex("CohorteId", "NumeroEtape")
                        .IsUnique();

                    b.ToTable("CohorteEtapeValidations");
                });

            modelBuilder.Entity("Web.Data.CohorteMembre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CohorteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAjout")
                        .HasColumnType("datetime2");

                    b.Property<int>("MethodeAjout")
                        .HasColumnType("int");

                    b.Property<string>("UtilisateurId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.HasIndex("CohorteId", "UtilisateurId")
                        .IsUnique();

                    b.ToTable("CohorteMembres");
                });

            modelBuilder.Entity("Web.Data.Entities.Fonction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstActif")
                        .HasColumnType("bit");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Fonctions");
                });

            modelBuilder.Entity("Web.Data.Entities.Organisation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adresse2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeAdherent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodePostal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstActif")
                        .HasColumnType("bit");

                    b.Property<string>("RaisonSociale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelephoneStandard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ville")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("Web.Data.Entities.Scope", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstActif")
                        .HasColumnType("bit");

                    b.Property<int?>("OrganisationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("OrganisationId");

                    b.ToTable("Scopes");
                });

            modelBuilder.Entity("Web.Data.ForumMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuteurId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ChallengeEtapeId")
                        .HasColumnType("int");

                    b.Property<int>("CohorteId")
                        .HasColumnType("int");

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MessageParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuteurId");

                    b.HasIndex("ChallengeEtapeId");

                    b.HasIndex("CohorteId");

                    b.HasIndex("MessageParentId");

                    b.ToTable("ForumMessages");
                });

            modelBuilder.Entity("Web.Data.ForumMessageUtile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("MarqueParId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MessageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MarqueParId");

                    b.HasIndex("MessageId", "MarqueParId")
                        .IsUnique();

                    b.ToTable("ForumMessagesUtiles");
                });

            modelBuilder.Entity("Web.Data.InvitationCompte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstActif")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ExpireLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UtilisateurId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UtiliseLe")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UtilisateurId");

                    b.ToTable("InvitationsComptes");
                });

            modelBuilder.Entity("Web.Data.NotificationInApp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Lu")
                        .HasColumnType("bit");

                    b.Property<string>("MessageCourt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReferenceId")
                        .HasColumnType("int");

                    b.Property<int>("ReferenceType")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UtilisateurId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId", "Lu", "DateCreation");

                    b.ToTable("NotificationsInApp");
                });

            modelBuilder.Entity("Web.Data.PointsEvenement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CohorteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Montant")
                        .HasColumnType("int");

                    b.Property<int>("Motif")
                        .HasColumnType("int");

                    b.Property<int>("ReferenceId")
                        .HasColumnType("int");

                    b.Property<int>("ReferenceType")
                        .HasColumnType("int");

                    b.Property<int>("TypePoints")
                        .HasColumnType("int");

                    b.Property<string>("UtilisateurId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CohorteId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("PointsEvenements");
                });

            modelBuilder.Entity("Web.Data.Preuve", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChallengeEtapeId")
                        .HasColumnType("int");

                    b.Property<int>("CohorteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateDepot")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<string>("UtilisateurId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeEtapeId");

                    b.HasIndex("CohorteId");

                    b.HasIndex("UtilisateurId", "ChallengeEtapeId")
                        .IsUnique();

                    b.ToTable("Preuves");
                });

            modelBuilder.Entity("Web.Data.PreuveFichier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CheminStockage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateUpload")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomFichier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PreuveId")
                        .HasColumnType("int");

                    b.Property<long>("TailleOctets")
                        .HasColumnType("bigint");

                    b.Property<int>("TypeFichier")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PreuveId");

                    b.ToTable("PreuveFichiers");
                });

            modelBuilder.Entity("Web.Data.PreuveValidationGestionnaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Commentaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateValidation")
                        .HasColumnType("datetime2");

                    b.Property<int>("Decision")
                        .HasColumnType("int");

                    b.Property<int>("PreuveId")
                        .HasColumnType("int");

                    b.Property<string>("ValideurId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PreuveId");

                    b.HasIndex("ValideurId");

                    b.ToTable("PreuveValidationsGestionnaire");
                });

            modelBuilder.Entity("Web.Data.PreuveValidationPair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Commentaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateValidation")
                        .HasColumnType("datetime2");

                    b.Property<int>("Decision")
                        .HasColumnType("int");

                    b.Property<int>("PreuveId")
                        .HasColumnType("int");

                    b.Property<string>("ValideurId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ValideurId");

                    b.HasIndex("PreuveId", "ValideurId")
                        .IsUnique();

                    b.ToTable("PreuveValidationsPairs");
                });

            modelBuilder.Entity("Web.Data.Rattachement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstActif")
                        .HasColumnType("bit");

                    b.Property<int?>("FonctionId")
                        .HasColumnType("int");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("FonctionId");

                    b.HasIndex("OrganisationId");

                    b.ToTable("Rattachements");
                });

            modelBuilder.Entity("Web.Data.RoleDroit", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DroitId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "DroitId");

                    b.HasIndex("DroitId");

                    b.ToTable("RoleDroits");
                });

            modelBuilder.Entity("Web.Data.RoleGroupeDroit", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GroupeDroitId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "GroupeDroitId");

                    b.HasIndex("GroupeDroitId");

                    b.ToTable("RoleGroupesDroit");
                });

            modelBuilder.Entity("Domain.Entities.CarteCompetence", b =>
                {
                    b.HasOne("Domain.Entities.Badge", "Badge")
                        .WithMany()
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Badge");
                });

            modelBuilder.Entity("Domain.Entities.ChallengeEtape", b =>
                {
                    b.HasOne("Domain.Entities.Challenge", "Challenge")
                        .WithMany("Etapes")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");
                });

            modelBuilder.Entity("Domain.Entities.ChallengeEtapeCarte", b =>
                {
                    b.HasOne("Domain.Entities.CarteCompetence", "CarteCompetence")
                        .WithMany()
                        .HasForeignKey("CarteCompetenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ChallengeEtape", "ChallengeEtape")
                        .WithMany("Cartes")
                        .HasForeignKey("ChallengeEtapeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarteCompetence");

                    b.Navigation("ChallengeEtape");
                });

            modelBuilder.Entity("Domain.Entities.Droit", b =>
                {
                    b.HasOne("Domain.Entities.GroupeDroit", "GroupeDroit")
                        .WithMany("Droits")
                        .HasForeignKey("GroupeDroitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.Ressource", "Ressource")
                        .WithMany("Droits")
                        .HasForeignKey("RessourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TypeAction", "TypeAction")
                        .WithMany("Droits")
                        .HasForeignKey("TypeActionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GroupeDroit");

                    b.Navigation("Ressource");

                    b.Navigation("TypeAction");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Web.Data.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Web.Data.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Web.Data.AcceptationDocumentLegal", b =>
                {
                    b.HasOne("Web.Data.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.DocumentLegal", "DocumentLegal")
                        .WithMany()
                        .HasForeignKey("DocumentLegalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("DocumentLegal");
                });

            modelBuilder.Entity("Web.Data.ApplicationUser", b =>
                {
                    b.HasOne("Web.Data.Civilite", "Civilite")
                        .WithMany()
                        .HasForeignKey("CiviliteId");

                    b.Navigation("Civilite");
                });

            modelBuilder.Entity("Web.Data.BadgeSocialAttribution", b =>
                {
                    b.HasOne("Domain.Entities.ChallengeEtape", "ChallengeEtape")
                        .WithMany()
                        .HasForeignKey("ChallengeEtapeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Web.Data.Cohorte", "Cohorte")
                        .WithMany()
                        .HasForeignKey("CohorteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Web.Data.ApplicationUser", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChallengeEtape");

                    b.Navigation("Cohorte");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Web.Data.CarteAttribution", b =>
                {
                    b.HasOne("Web.Data.ApplicationUser", "AttribuePar")
                        .WithMany()
                        .HasForeignKey("AttribueParId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.CarteCompetence", "CarteCompetence")
                        .WithMany()
                        .HasForeignKey("CarteCompetenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ChallengeEtape", "ChallengeEtape")
                        .WithMany()
                        .HasForeignKey("ChallengeEtapeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Web.Data.Cohorte", "Cohorte")
                        .WithMany()
                        .HasForeignKey("CohorteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Web.Data.ApplicationUser", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttribuePar");

                    b.Navigation("CarteCompetence");

                    b.Navigation("ChallengeEtape");

                    b.Navigation("Cohorte");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Web.Data.Cohorte", b =>
                {
                    b.HasOne("Domain.Entities.Challenge", "Challenge")
                        .WithMany()
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Web.Data.Entities.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Challenge");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("Web.Data.CohorteEtapeValidation", b =>
                {
                    b.HasOne("Web.Data.Cohorte", "Cohorte")
                        .WithMany()
                        .HasForeignKey("CohorteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web.Data.ApplicationUser", "ValidePar")
                        .WithMany()
                        .HasForeignKey("ValideParId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cohorte");

                    b.Navigation("ValidePar");
                });

            modelBuilder.Entity("Web.Data.CohorteMembre", b =>
                {
                    b.HasOne("Web.Data.Cohorte", "Cohorte")
                        .WithMany("Membres")
                        .HasForeignKey("CohorteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web.Data.ApplicationUser", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cohorte");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Web.Data.Entities.Scope", b =>
                {
                    b.HasOne("Web.Data.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web.Data.Entities.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApplicationUser");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("Web.Data.ForumMessage", b =>
                {
                    b.HasOne("Web.Data.ApplicationUser", "Auteur")
                        .WithMany()
                        .HasForeignKey("AuteurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ChallengeEtape", "ChallengeEtape")
                        .WithMany()
                        .HasForeignKey("ChallengeEtapeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Web.Data.Cohorte", "Cohorte")
                        .WithMany()
                        .HasForeignKey("CohorteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Web.Data.ForumMessage", "MessageParent")
                        .WithMany("Reponses")
                        .HasForeignKey("MessageParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Auteur");

                    b.Navigation("ChallengeEtape");

                    b.Navigation("Cohorte");

                    b.Navigation("MessageParent");
                });

            modelBuilder.Entity("Web.Data.ForumMessageUtile", b =>
                {
                    b.HasOne("Web.Data.ApplicationUser", "MarquePar")
                        .WithMany()
                        .HasForeignKey("MarqueParId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Web.Data.ForumMessage", "Message")
                        .WithMany("MarquagesUtile")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarquePar");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Web.Data.InvitationCompte", b =>
                {
                    b.HasOne("Web.Data.ApplicationUser", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Web.Data.NotificationInApp", b =>
                {
                    b.HasOne("Web.Data.ApplicationUser", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Web.Data.PointsEvenement", b =>
                {
                    b.HasOne("Web.Data.Cohorte", "Cohorte")
                        .WithMany()
                        .HasForeignKey("CohorteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Web.Data.ApplicationUser", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cohorte");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Web.Data.Preuve", b =>
                {
                    b.HasOne("Domain.Entities.ChallengeEtape", "ChallengeEtape")
                        .WithMany()
                        .HasForeignKey("ChallengeEtapeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Web.Data.Cohorte", "Cohorte")
                        .WithMany()
                        .HasForeignKey("CohorteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Web.Data.ApplicationUser", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChallengeEtape");

                    b.Navigation("Cohorte");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Web.Data.PreuveFichier", b =>
                {
                    b.HasOne("Web.Data.Preuve", "Preuve")
                        .WithMany("Fichiers")
                        .HasForeignKey("PreuveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Preuve");
                });

            modelBuilder.Entity("Web.Data.PreuveValidationGestionnaire", b =>
                {
                    b.HasOne("Web.Data.Preuve", "Preuve")
                        .WithMany("ValidationsGestionnaire")
                        .HasForeignKey("PreuveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web.Data.ApplicationUser", "Valideur")
                        .WithMany()
                        .HasForeignKey("ValideurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Preuve");

                    b.Navigation("Valideur");
                });

            modelBuilder.Entity("Web.Data.PreuveValidationPair", b =>
                {
                    b.HasOne("Web.Data.Preuve", "Preuve")
                        .WithMany("ValidationsPairs")
                        .HasForeignKey("PreuveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web.Data.ApplicationUser", "Valideur")
                        .WithMany()
                        .HasForeignKey("ValideurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Preuve");

                    b.Navigation("Valideur");
                });

            modelBuilder.Entity("Web.Data.Rattachement", b =>
                {
                    b.HasOne("Web.Data.ApplicationUser", "ApplicationUser")
                        .WithMany("Rattachements")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web.Data.Entities.Fonction", "Fonction")
                        .WithMany()
                        .HasForeignKey("FonctionId");

                    b.HasOne("Web.Data.Entities.Organisation", "Organisation")
                        .WithMany("Rattachements")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Fonction");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("Web.Data.RoleDroit", b =>
                {
                    b.HasOne("Domain.Entities.Droit", "Droit")
                        .WithMany()
                        .HasForeignKey("DroitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web.Data.ApplicationRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Droit");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Web.Data.RoleGroupeDroit", b =>
                {
                    b.HasOne("Domain.Entities.GroupeDroit", "GroupeDroit")
                        .WithMany()
                        .HasForeignKey("GroupeDroitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web.Data.ApplicationRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupeDroit");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.Challenge", b =>
                {
                    b.Navigation("Etapes");
                });

            modelBuilder.Entity("Domain.Entities.ChallengeEtape", b =>
                {
                    b.Navigation("Cartes");
                });

            modelBuilder.Entity("Domain.Entities.GroupeDroit", b =>
                {
                    b.Navigation("Droits");
                });

            modelBuilder.Entity("Domain.Entities.Ressource", b =>
                {
                    b.Navigation("Droits");
                });

            modelBuilder.Entity("Domain.Entities.TypeAction", b =>
                {
                    b.Navigation("Droits");
                });

            modelBuilder.Entity("Web.Data.ApplicationUser", b =>
                {
                    b.Navigation("Rattachements");
                });

            modelBuilder.Entity("Web.Data.Cohorte", b =>
                {
                    b.Navigation("Membres");
                });

            modelBuilder.Entity("Web.Data.Entities.Organisation", b =>
                {
                    b.Navigation("Rattachements");
                });

            modelBuilder.Entity("Web.Data.ForumMessage", b =>
                {
                    b.Navigation("MarquagesUtile");

                    b.Navigation("Reponses");
                });

            modelBuilder.Entity("Web.Data.Preuve", b =>
                {
                    b.Navigation("Fichiers");

                    b.Navigation("ValidationsGestionnaire");

                    b.Navigation("ValidationsPairs");
                });
#pragma warning restore 612, 618
        }
    }
}
